services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.33.0
    restart: unless-stopped
    ports:
      - 10000:10000
    volumes:
      - azurite-data:/data
  redis:
    image: redis:7.4.2-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
  codepush:
    build:
      context: ./api
      dockerfile: ../Dockerfile
    image: ghcr.io/hoang-rio/code-push-server:latest
    restart: unless-stopped
    ports:
      - ${PORT:-3000}:3000
    environment:
      EMULATED: true
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      SERVER_URL: ${SERVER_URL}
      AZURITE_HOST: azurite
      AZURITE_URL: ${AZURITE_URL}
      REDIS_HOST: redis
    depends_on:
      - azurite
      - redis

volumes:
  azurite-data:
  redis-data: