name: "Docker image build and deploy"

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  SSH_KEY_FILE_DIR: .keys
  SSH_KEY_FILE_PATH: .keys/deploy_key.pem
  HAS_API_CHANGED: false

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Check if API has changed
        id: check_api_changed
        run: |
          if [[ $(git show --name-only --pretty="" ${{ github.sha }} | grep -q api/) ]]; then
            echo "API has changed"
            echo "HAS_API_CHANGED=true" >> $GITHUB_ENV
          else
            echo "API has not changed"
          fi
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        if: ${{ env.HAS_API_CHANGED == 'true' }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        if: ${{ env.HAS_API_CHANGED == 'true' }}
        run: |
          docker compose build --push
  deploy:
    runs-on: ubuntu-24.04
    needs: [build]
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Create deploy key file
        run: |
          mkdir ${{env.SSH_KEY_FILE_DIR}}
          echo "${{secrets.SSH_DEPLOY_KEY}}" > ${{env.SSH_KEY_FILE_PATH}}
          chmod 600 ${{env.SSH_KEY_FILE_PATH}}
      - name: Deploy with ssh
        run: |
          rsync -have "ssh -i ${{env.SSH_KEY_FILE_PATH}} -o StrictHostKeyChecking=no" docker-compose.yml ${{secrets.SSH_DEPLOY_USER}}@${{secrets.SSH_DEPLOY_HOST}}:${{secrets.SSH_DEPLOY_PATH}}/
          ssh -i ${{env.SSH_KEY_FILE_PATH}} -o StrictHostKeyChecking=no ${{secrets.SSH_DEPLOY_USER}}@${{secrets.SSH_DEPLOY_HOST}} "cd ${{secrets.SSH_DEPLOY_PATH}}/ && docker compose pull && docker compose up -d && docker image prune -af"
